<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ticket extends Model
{
    protected $fillable = [
        'ticket_customer_id', 'validation_token','qr_code_image_url','pdf_format_url','unique_ID',
        'ticket_category_detail_id','ticket_price','event_id'
    ];

    //let's append the price of each ticket
    protected $appends=['ticket_price'];

    public function getTicketPriceAttribute()
    {
        return $this->ticket_category_detail->price;
    }

//    public function newQuery()
//    {
//        return parent::newQuery()->select('tickets.*'); // TODO: Change the autogenerated stub
//    }

    public function ticket_category_detail()
    {
        return $this->hasOne('App\TicketCategoryDetail','id','ticket_category_detail_id');
    }

    public function event()
    {
        return $this->belongsTo('App\Event', 'event_id');
    }

//    public function category()
//    {
//        return $this->ticket_category_detail->category();
//    }

    public function ticket_scan()
    {
        return $this->hasOne('App\TicketScan', 'ticket_id');
    }

    public function ticket_customer()
    {
        return $this->belongsTo('App\TicketCustomer', 'ticket_customer_id');
    }


    /**
     * check whether this ticket has been scanned yet
     * @return bool
     */
    public function scanned()
    {
        if ($this->ticket_scan == null) {return false;}
        else {
            return $this->ticket_scan->count() == 1 ? true : false;
        }
    }
}
